###Hello to everyone
POST http://localhost:8081/auth/login
Content-Type: application/json

{
    "email": "a@ba.ru",
    "password": "qweasdzxc"
}

###HEllo to me
POST http://localhost:8081/auth/register
Content-Type: application/json

{
    "name": "IVAn",
    "email": "a@a.ru",
    "password": "qweasdzxc"
}

###Delete link
DELETE http://localhost:8081/link/3

###Create link
POST http://localhost:8081/link 
Content-Type: application/json

{
    "url": "https://github.com"
}


###GoTo link
GET http://localhost:8081/trWEsc HTTP/1.1

###Update link
PATCH http://localhost:8081/link/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUifQ.AuEKIYp9_ppBx6P7HWeBaiNBC2Mu61CgxZiVo4AJLRs

{
    "url":"http://vk.com"
    
}

###Get links
GET http://localhost:8081/link?limit=5&offset=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUifQ.AuEKIYp9_ppBx6P7HWeBaiNBC2Mu61CgxZiVo4AJLRs

###Get stats
GET http://localhost:8081/stat?from=2025-04-01&to=2025-04-07&by=day
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYmEucnUifQ.AuEKIYp9_ppBx6P7HWeBaiNBC2Mu61CgxZiVo4AJLRs
